name: Child Workflow

on:
  workflow_run:
    workflows: ["derived/Parent Workflow"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2


