name: Child Workflow

on:
  repository_dispatch:
    types: [trigger-workflow-b]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: directories
        run: ls
        
