name: Child Workflow

on:
  workflow_call:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: directories
        run: ls
        
