name: Child Pipeline 2

on:
  workflow_run:
    workflows: ["Parent Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Child Step 2
        run: echo "Child Step 2 executed"
