name: Child Pipeline 1

on:
  workflow_run:
    workflows: ["Parent Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Child Step 1
        run: echo "Child Step 1 executed"
