name: MATLAB

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v0
        with:
          matlab-version: R2021a

      - name: Run MATLAB script
        run: matlab -r "disp('Hello, MATLAB!');"

      # Rest of the build steps...
