name: Parent Workflow

on:
  workflow_run:
    workflows: ["Child Workflow"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Other steps of the workflow
