name: pipeline2
on:
  workflow_dispatch:


permissions:
    contents: read
    checks: write
    
env:
  PATH_TO_MATLAB: "\\\\mathworks\\devel\\sbs\\37\\vanshg.Bslcicd.j2276893.1\\matlab\\bin"
  #GITHUB_PATH: # Add the gitub variable path here
  
jobs:
  AHRS_Generate_Simulink_Web_View:
    runs-on: Linux
    if: ${{ always() }}
    steps:


      - name: Cache files
        uses: actions/cache@v2
        with:
          path: |
            04_Results/AHRS_Voter/code_inspection
            04_Results/AHRS_Voter/coding_standards
            04_Results/AHRS_Voter/design_error_detections
            04_Results/AHRS_Voter/model_standards_results
            04_Results/AHRS_Voter/system_design_description
            04_Results/AHRS_Voter/webview
            04_Results/Actuator_Control/code_inspection
            04_Results/Actuator_Control/coding_standards
            04_Results/Actuator_Control/design_error_detections
            04_Results/Actuator_Control/model_standards_results
            04_Results/Actuator_Control/system_design_description
            04_Results/Actuator_Control/webview
            04_Results/Flight_Control/code_inspection
            04_Results/Flight_Control/coding_standards
            04_Results/Flight_Control/design_error_detections
            04_Results/Flight_Control/model_standards_results
            04_Results/Flight_Control/system_design_description
            04_Results/Flight_Control/webview
            04_Results/InnerLoop_Control/code_inspection
            04_Results/InnerLoop_Control/coding_standards
            04_Results/InnerLoop_Control/design_error_detections
            04_Results/InnerLoop_Control/model_standards_results
            04_Results/InnerLoop_Control/system_design_description
            04_Results/InnerLoop_Control/webview
            04_Results/OuterLoop_Control/code_inspection
            04_Results/OuterLoop_Control/coding_standards
            04_Results/OuterLoop_Control/design_error_detections
            04_Results/OuterLoop_Control/model_standards_results
            04_Results/OuterLoop_Control/system_design_description
            04_Results/OuterLoop_Control/webview
            04_Results/test_results
          key: cached-files
        
      - name: Run the matlab version
        run: $env:PATH += ";$env:PATH_TO_MATLAB"; $env:PATH | Add-Content -Path $env:GITHUB_PATH

         
      - name: Launch MATLAB
        uses: matlab-actions/run-command@v1
        with:
             command: "openProject(pwd);runprocess(Tasks = {'padv.builtin.task.GenerateSimulinkWebView|sl_model_file|ProcessAdvisorExample|02_Models/AHRS_Voter/specification/AHRS_Voter.slx'}, Force=false,ExitInBatchMode = true, RerunFailedTasks = false,RerunErroredTasks = false,GenerateJUnitForProcess = true);"
             startup-options: -nodesktop -logfile output.log
 
          
      - name: AHRS_Voter_JUnit
        uses: mikepenz/action-junit-report@v3
        with:
          name: AHRS_Voter
          report_paths: 04_Results/junit/padv_builtin_task_GenerateSimulinkWebView_AHRS_Voter_JUnit.xml
          
  AHRS_Check_Modeling_Standards:
   runs-on: self-hosted
   if: ${{ always() }}
   needs: AHRS_Generate_Simulink_Web_View
   steps:
   
     
   - name: Run the matlab version
     run: $env:PATH += ";$env:PATH_TO_MATLAB"; $env:PATH | Add-Content -Path $env:GITHUB_PATH  
        
   - name: Launch MATLAB
     uses: matlab-actions/run-command@v1
     with:
         command: "openProject(pwd);runprocess(Tasks = {'padv.builtin.task.RunModelStandards|sl_model_file|ProcessAdvisorExample|02_Models/AHRS_Voter/specification/AHRS_Voter.slx'}, Force=false,ExitInBatchMode = true, RerunFailedTasks = false,RerunErroredTasks = false,GenerateJUnitForProcess = true);"
         startup-options: -nodesktop -logfile output.log
 
          
   - name: AHRS_Voter_JUnit
     uses: mikepenz/action-junit-report@v3
     with:
        name: AHRS_Voter
        report_paths: 04_Results/junit/padv_builtin_task_RunModelStandards_AHRS_Voter_JUnit.xml
   
  AHRS_Detect_Design_Errors:
   runs-on: self-hosted
   needs: AHRS_Check_Modeling_Standards
   if: ${{ always() }}
   steps: 

   - name: Run the matlab version
     run: $env:PATH += ";$env:PATH_TO_MATLAB"; $env:PATH | Add-Content -Path $env:GITHUB_PATH 
         
   - name: Launch MATLAB
     uses: matlab-actions/run-command@v1
     with:
         command: "openProject(pwd);runprocess(Tasks = {'padv.builtin.task.DetectDesignErrors|sl_model_file|ProcessAdvisorExample|02_Models/AHRS_Voter/specification/AHRS_Voter.slx'}, Force=false,ExitInBatchMode = true, RerunFailedTasks = false,RerunErroredTasks = false,GenerateJUnitForProcess = true);"
         startup-options: -nodesktop -logfile output.log
          
   - name: AHRS_Voter_JUnit
     uses: mikepenz/action-junit-report@v3
     with:
        name: AHRS_Voter
        report_paths: 04_Results/junit/padv_builtin_task_DetectDesignErrors_AHRS_Voter_JUnit.xml
